### ISSUE TITLE
vagues.spwn

### ISSUE THREAD

**Issue by SpeckyYT** [Harksa/2942#1]
Why does `vagues.spwn` have the `spwn` extension?

**Comment by m1kadev** [comment]
cuz its a cool file

**Comment by slotling** [comment]
[me discovering the first spwn repository](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by MiloLug** [comment]
Explain it, sweetie. Why spwn?

**Comment by Harksa** [comment]
Please, kindly don't open an issue about the extension of a file from a projet that is 4 years old that I named that way because it  was txt files used to SPaWN ennemies.
